### ISSUE TITLE
New Spec TODO

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie.github.io#5]
**Tentative Spec-Changes:**
- [x] `sourceLocations` -> `dataLocations` or `xmlLocations`?
- [x] dataset metadata: exact definition of `dataset`?
- [x] do we need project metadata in `project.json`? I think `references` should be in there.
- [x] grid-view table layout: https://github.com/mobie/mobie/issues/22#issuecomment-803476419
- [x] `menuItem` format: https://github.com/mobie/mobie-viewer-fiji/issues/200#issuecomment-803475881

**Json Schema and spec description:**
Proper string regex:
- [x] source.menuItem: `menuName/itemName`
- [x] source.sourceLocations: pattern for xml file path
- [x] segmentationSource.tableRootLocation: pattern for folder
- [x] imagedisplays.color: RGBApattern (`"\\(r=(.+),g=(.+),b=(.+),a=(.+)\\)"`) and `randomFromGlasbey`
- [x] segmentationDisplays.color: double check allowed values,  color map from file, [example](https://github.com/mobie/covid-em-datasets/blob/master/data/Covid19-S4-Area2/images/images.json#L3)
- [x] segmentationDisplays.selectedSegmentIds: `sourceName;timepoint;labelId`
- [x] project.specVersion: `MAJOR.MINOR.PATCH`
- [x] all `name` fields: no whitespaces, no `;`, no `/`

**Tooling:**
- [x] Auto generate parts of spec from json schema, useful tools: [fake-schema-cli](https://github.com/atomsfat/fake-schema-cli#readme), [jsonschema2md](https://github.com/adobe/jsonschema2md), [json-schema-to-markdown](https://github.com/saibotsivad/json-schema-to-markdown)
- [ ] CI for static json schema validation (create github actions? https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)
- [x] Fix issue with example generation for `source.schema`

**Spec description**:

- [ ] The examples generated by *schema-faker* don't look very nice (weird names where it needs to match the regexps) and are inconsistent where consistency cannot be enforced through the schema (e.g. `sources` not matching `name`). Would be best to write some code around this to choose better names and make things consistent or write the examples manually once we fix the current spec version.

**Comment by constantinpape** [comment]
From discussion with @tischi 
- `imageDataLocations`, `tableDataLocations`
- `references` to project, `dimensions`: {`is2d`: `true`/`false`}

**Comment by constantinpape** [comment]
Also, the bookmark description will be outdated with the new spec: https://mobie.github.io/tutorials/bookmarks.html

**Comment by constantinpape** [comment]
Remaining regex issues:
- `[^\/]+\/[^\/]+` matches the menuItem `a/b` pattern, but it still allows for matching `a/b/c/...`

**Comment by constantinpape** [comment]
More spec changes:
- Move `description` and `is2d` to root level and get rid of `dataset` in dataset spec; move `description` and `references` to root level and get rid of `project` in project spec, see #6.
- Remove `name` in `sourceTrasforms:affine`? see #7
- Rename `tableDataRootLocation` to `tableDataLocation` for `segmentationSource` and `autoGrid`, see #9
- `imageDisplays` -> `imageDisplay`, `segmentationDisplays` -> `segmentationDisplay`, see #10

**Comment by constantinpape** [comment]
Add `viewerTransform` to the example.

**Comment by constantinpape** [comment]
Above is done, new set of changes:
- Rename `color` to `lut` in `segmentationDisplay`, see #16.
- Add fields for scatterplot to `segmentationDisplay` (exact format is still under discussion), see https://github.com/mobie/mobie-viewer-fiji/issues/224
